import type { Config } from "tailwindcss";
import animate from "tailwindcss-animate";
import typography from "@tailwindcss/typography";

const config = {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        background: "#FFFFFF",
        card: "#FFFFFF",
        border: "#E5E5E5",
        foreground: "#191919",
        "muted-foreground": "#737373",
        primary: "#191919",
        "primary-foreground": "#FFFFFF",
        popover: "#FFFFFF",
        "popover-foreground": "#191919",
        input: "#E5E5E5",
        ring: "#191919",
        secondary: "#F7F6F3",
        "secondary-foreground": "#37352F",
        destructive: "#EB5757",
        "destructive-foreground": "#FFFFFF",
        accent: "#37352F",
        "accent-foreground": "#FFFFFF",
        success: "#2ECC71",
        warning: "#F5C542",
        danger: "#EB5757",
        muted: "#F7F6F3",
        "icon-muted": "#A0A0A0",
        "chart-5": "#555555",
        dataset: "#37352F",
        setting: "#555555",
        "queue-status-red": "#EB5757",
        sidebar: "#FFFFFF",
        "sidebar-foreground": "#37352F",
        "sidebar-accent": "#F7F6F3",
        "sidebar-accent-foreground": "#37352F",
        "sidebar-border": "#E5E5E5",
        "sidebar-ring": "#37352F",
        gray: {
          50: "#FAFAFA",
          100: "#F7F6F3",
          200: "#E5E5E5",
          300: "#D4D4D4",
          400: "#A0A0A0",
          500: "#737373",
          600: "#555555",
          700: "#37352F",
          800: "#2D2D2D",
          900: "#191919",
        },
        amber: {
          50: "#fffbeb",
          100: "#fef3c7",
          200: "#fde68a",
          300: "#fcd34d",
          400: "#fbbf24",
          500: "#f59e0b",
          600: "#d97706",
          700: "#b45309",
          800: "#92400e",
          900: "#191919",
        },
      },
      boxShadow: {
        soft: "0 1px 3px rgba(0,0,0,0.04), 0 1px 2px rgba(0,0,0,0.06)",
        float: "0 4px 12px rgba(0,0,0,0.08), 0 1px 3px rgba(0,0,0,0.04)",
      },
      borderRadius: {
        xl: "0.75rem",
        "2xl": "1rem",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        float: {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-5%)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        float: "float 3s ease-in-out infinite",
      },
    },
  },
  safelist: [
    "bg-primary/10",
    "bg-accent/10",
    "bg-chart-5/10",
    "hover:bg-primary/5",
    "hover:bg-accent/5",
    "hover:bg-chart-5/5",
    "hover:border-primary/30",
    "hover:border-accent/30",
    "hover:border-chart-5/30",
    "group-hover:bg-primary",
    "group-hover:bg-accent",
    "group-hover:bg-chart-5",
    "text-primary",
    "text-accent",
    "text-chart-5",
    "group-hover:text-white",
    "bg-primary/10",
    "text-primary",
    "bg-accent/10",
    "text-accent",
    "bg-chart-5/10",
    "text-chart-5",
    "border-primary/20",
    "border-accent/20",
    "border-chart-5/20",
    "group-hover:bg-primary/20",
    "group-hover:bg-accent/20",
    "group-hover:bg-chart-5/20",
    "bg-dataset/10",
    "text-dataset",
    "border-dataset/20",
    "group-hover:bg-dataset/20",
    "bg-setting/10",
    "text-setting",
    "border-setting/20",
    "group-hover:bg-setting/20",
    "bg-dataset/5",
    "hover:bg-dataset/90",
    "border-dataset/30",
    "hover:bg-dataset/10",
  ],
  plugins: [animate, typography],
} satisfies Config;

export default config;
